import { createAction, props } from "@ngrx/store";
import { LoginModel } from "src/app/model/loginModel";
import { EditUserModel, UserModel } from "src/app/model/userModel";

export const LOGIN_USER = '[admin page] login user';
export const LOGIN_USER_SUCCESS = '[admin page] login user success';
export const LOGIN_USER_FAIL = '[admin page] login user fail';
export const GET_USERS = '[admin page] get users';
export const GET_USERS_SUCCESS = '[admin page] get users success';
export const GET_USERS_FAIL = '[admin page] get users fail';
export const GET_USER = '[admin page] get user';
export const GET_USER_SUCCESS = '[admin page] get user success';
export const GET_USER_FAIL = '[admin page] get user fail';
export const ADD_USER = '[admin page] add user';
export const ADD_USER_SUCCESS = '[admin page] add user success';
export const ADD_USER_FAIL = '[admin page] add user fail';
export const DELETE_USER = '[admin page] delete user';
export const DELETE_USER_SUCCESS = '[admin page] delete user success';
export const DELETE_USER_FAIL = '[admin page] delete user fail';
export const PUT_USER = '[admin page] put user';
export const PUT_USER_SUCCESS = '[admin page] put user success';
export const PUT_USER_FAIL = '[admin page] put user fail';
export const UPLOAD_USER_IMG = '[admin page] put user';

export const loginUser = createAction(LOGIN_USER, props<{inputData:LoginModel}>());
export const loginUserSuccess = createAction(LOGIN_USER_SUCCESS, props<{user:UserModel}>());
export const loginUserFail = createAction(LOGIN_USER_FAIL, props<{errMsg:string}>());
export const getUsers = createAction(GET_USERS);
export const getUsersSuccess = createAction(GET_USERS_SUCCESS, props<{users:UserModel[]}>());
export const getUsersFail = createAction(GET_USERS_FAIL, props<{errMsg:string}>());
export const getUser = createAction(GET_USER, props<{id:string}>());
export const getUserSuccess = createAction(GET_USER_SUCCESS, props<{user:UserModel}>());
export const getUserFail = createAction(GET_USER_FAIL, props<{errMsg:string}>());
export const addUser = createAction(ADD_USER, props<{inputData:UserModel}>());
export const addUserSuccess = createAction(ADD_USER_SUCCESS, props<{user:UserModel}>());
export const addUserFail = createAction(ADD_USER_FAIL, props<{errMsg:string}>());
export const deleteUser = createAction(DELETE_USER, props<{id:string}>());
export const deleteUserSuccess = createAction(DELETE_USER_SUCCESS, props<{user:UserModel}>());
export const deleteUserFail = createAction(DELETE_USER_FAIL, props<{errMsg:string}>());
export const putUser = createAction(PUT_USER, props<{inputData:EditUserModel}>());
export const putUserSuccess = createAction(PUT_USER_SUCCESS, props<{user:UserModel}>());
export const putUserFail = createAction(PUT_USER_FAIL, props<{errMsg:string}>());
export const uploadUserImg = createAction(UPLOAD_USER_IMG, props<{id:string, image:FormData}>());